name: ci
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pull gb studio from repo
      run: git clone https://github.com/chrismaltby/gb-studio.git
    - name: install gb studio 
      working-directory: gb-studio 
      run: |
        git submodule update --init --recursive
        # npm install -g corepack
        corepack enable
        yarn
        npm start
        npm run make:cli
        yarn link
        $(yarn bin gb-studio-cli) -V
        $(yarn bin gb-studio-cli) make:rom ../bubblequack.gbsproj ../out/bubblequack.gbc
        $(yarn bin gb-studio-cli) make:web ../bubblequack.gbsproj ../html

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bubblequack
        path: gb-studio/out/bubblqequack.gbc

    - name: Deploy to GitHub Pages 🚀        
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        folder: gb-studio/html

